### PR TITLE
the colored image preserves the image extension

### PR DESCRIPTION
**Pull request by RezaRazmara**
Hi Yash Arora 
in this commit, you just select image with any file extension, and after that you can download it with its original image extension.

### CODE REVIEW

**Review by yasharora102 — CHANGES_REQUESTED** [review]
Hello there @RezaRazmara, glad to see your PR. 
After going through the code there are 3 things I want to address:

1. I guess you forgot to import the helper.py script inside `app.py` so there's no extension argument given to the `colorize_image()` function.

This is the output from the terminal after hitting submit.
Screenshot 2023-05-15 at 11 05 55 PM

2. No need to provide new files in the Original Directory, they are there for the README.

3. I see that you've made a new `result.html` for the download if you plan on using that link it as a TemplateResponse

Screenshot 2023-05-15 at 11 15 44 PM

Refer to this code: this is for returning the `upload.html`
```python
return templates.TemplateResponse("upload.html", {"request": request})
```

Go through the code again and make the modifications accordingly. Thanks for the contribution.

**Comment by RezaRazmara** [comment]
hi @yasharora102 
Thanks for your informative response.
I made the changes.  please test it. for not adding helper module I don't have any idea. so what is your suggestion ?
Thansk
e235cc008cf8882606b2cbfafeb32110b2858f28

**Review by yasharora102 — CHANGES_REQUESTED** [review]
@RezaRazmara, Regarding the `helper` I just mentioned that you forgot to import it in the main script. (You've fixed it now)
Everything seems working fine now, just 2 more things I would like to mention:
1. Remove the `cameraman.tif` file as the `Original, Colorized` directories only contain files for the README
2. After you're done, run `black .` in the terminal just before you're committing, after that if you can squash your commits into one that would be nice.

**Comment by RezaRazmara** [comment]
@yasharora102 in this commit the changes you asked are made.
1. black . run
2. the .tiff image is deleted
https://github.com/yasharora102/image-colorization-api/pull/8/commits/e02e4582c0ad37d20135e8dfd93c2c97d2feb2c1

**Review by yasharora102 — CHANGES_REQUESTED** [review]
Hi @RezaRazmara, everything seems working fine, but I found an error while making a request via the CLI.
Screenshot 2023-05-16 at 1 20 25 PM


It seems that you forgot to add the extension in the CLI endpoint, to resolve this can you change the 35th line in `app.py` to 

```python
os.rename("colorized_image." + extension, "static/colorized_image." + extension)
```

Make the change and squash the commits into one, I'll merge it.

**Review by yasharora102 — APPROVED** [review]
LGTM 👍🏻
Closes #7

**Pull request merged**
